'use client'

import Image from 'next/image'
import Link from 'next/link'
import { Heart, Minus, Plus, Search, ShoppingBag, Trash2 } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { categories, formatPrice, getProduct, logoUrl, products, type Product } from '@/lib/catalog'

export function BrandHeader({ cartCount = 0, likeCount = 0 }: { cartCount?: number; likeCount?: number }) {
  return <header className="sticky top-0 z-30 border-b border-border bg-background/95 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between gap-4 px-4 py-3 sm:px-6"><Link href="/" className="flex shrink-0 items-center gap-2"><Image src={logoUrl} alt="Cocoa Bloom logo" width={42} height={42} className="size-10 rounded-full object-cover" /><span className="hidden font-serif text-2xl tracking-[-0.08em] sm:inline">Cocoa <i className="text-accent">Bloom</i></span></Link><nav className="hidden items-center gap-5 text-xs font-semibold uppercase tracking-[0.12em] md:flex"><Link href="/menu" className="hover:text-accent">Menu</Link><Link href="/likes" className="hover:text-accent">Likes ({likeCount})</Link></nav><div className="flex items-center gap-2"><Link href="/menu" className="hidden items-center gap-2 border border-border px-3 py-2 text-xs sm:flex"><Search size={15} /> Search</Link><Link href="/cart" aria-label={`Cart with ${cartCount} items`} className="flex items-center gap-2 bg-primary px-3 py-2 text-xs text-primary-foreground"><ShoppingBag size={16} /> Cart ({cartCount})</Link></div></div></header>
}

export function useStore() {
  const [likes, setLikes] = useState<string[]>([])
  const [cart, setCart] = useState<Record<string, number>>({})
  useEffect(() => { try { setLikes(JSON.parse(localStorage.getItem('cocoa-bloom-likes') || '[]')); setCart(JSON.parse(localStorage.getItem('cocoa-bloom-cart') || '{}')) } catch {} }, [])
  useEffect(() => {
    const sync = () => { try { setLikes(JSON.parse(localStorage.getItem('cocoa-bloom-likes') || '[]')); setCart(JSON.parse(localStorage.getItem('cocoa-bloom-cart') || '{}')) } catch {} }
    window.addEventListener('storage', sync); window.addEventListener('cocoa-bloom-sync', sync)
    return () => { window.removeEventListener('storage', sync); window.removeEventListener('cocoa-bloom-sync', sync) }
  }, [])
  const announce = () => { if (typeof window !== 'undefined') window.setTimeout(() => window.dispatchEvent(new Event('cocoa-bloom-sync')), 0) }
  useEffect(() => { localStorage.setItem('cocoa-bloom-likes', JSON.stringify(likes)) }, [likes])
  useEffect(() => { localStorage.setItem('cocoa-bloom-cart', JSON.stringify(cart)) }, [cart])
  const toggleLike = (id: string) => { setLikes((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]); announce() }
  const addToCart = (id: string) => { setCart((current) => ({ ...current, [id]: (current[id] || 0) + 1 })); announce() }
  const removeFromCart = (id: string) => { setCart((current) => { const next = { ...current }; delete next[id]; return next }); announce() }
  const updateCart = (id: string, amount: number) => { setCart((current) => ({ ...current, [id]: Math.max(1, amount) })); announce() }
  return { likes, cart, toggleLike, addToCart, removeFromCart, updateCart, cartCount: Object.values(cart).reduce((sum, count) => sum + count, 0) }
}

export function ProductRow({ product, liked, quantity = 0, onLike, onAdd, onUpdate }: { product: Product; liked: boolean; quantity?: number; onLike: () => void; onAdd: () => void; onUpdate?: (amount: number) => void }) {
  return <article className="flex gap-3 border-b border-border py-4"><div className="relative size-24 shrink-0 overflow-hidden bg-secondary sm:size-28"><Image src={product.image} alt={product.name} fill className="object-cover" sizes="112px" /></div><div className="min-w-0 flex-1"><div className="flex items-start justify-between gap-2"><div><div className="flex items-center gap-2"><h3 className="font-serif text-xl leading-tight">{product.name}</h3>{product.badge && <span className="bg-secondary px-1.5 py-0.5 text-[9px] font-semibold uppercase tracking-wider">{product.badge}</span>}</div><p className="mt-1 text-sm leading-5 text-muted-foreground">{product.description}</p></div><button aria-label={`${liked ? 'Remove' : 'Add'} ${product.name} to likes`} onClick={onLike} className="shrink-0 p-1 text-accent"><Heart size={18} fill={liked ? 'currentColor' : 'none'} /></button></div><div className="mt-3 flex items-center justify-between"><span className="font-mono text-sm font-semibold">{formatPrice(product.price)}</span>{quantity > 0 && onUpdate ? <div className="flex items-center gap-3 border border-border px-2 py-1"><button aria-label={`Decrease ${product.name}`} onClick={() => onUpdate(quantity - 1)}><Minus size={13} /></button><span className="font-mono text-xs">{quantity}</span><button aria-label={`Increase ${product.name}`} onClick={() => onUpdate(quantity + 1)}><Plus size={13} /></button></div> : <button onClick={onAdd} className="bg-accent px-4 py-2 text-[10px] font-semibold uppercase tracking-[0.14em] text-accent-foreground">Add</button>}</div></div></article>
}

export function MenuBrowser() {
  const store = useStore(); const [category, setCategory] = useState('All'); const [query, setQuery] = useState('')
  const filtered = useMemo(() => products.filter((product) => (category === 'All' || product.category === category) && `${product.name} ${product.description}`.toLowerCase().includes(query.toLowerCase())), [category, query])
  return <><div className="sticky top-[67px] z-20 border-b border-border bg-background px-4 py-3 sm:px-6"><div className="mx-auto flex max-w-6xl flex-col gap-3 sm:flex-row"><label className="flex flex-1 items-center gap-2 border border-border bg-card px-3 py-2"><Search size={16} className="text-muted-foreground" /><span className="sr-only">Search menu</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search for chocolate, bars, dates..." className="w-full bg-transparent text-sm outline-none placeholder:text-muted-foreground" /></label><div className="flex gap-2 overflow-x-auto">{categories.map((item) => <button key={item} onClick={() => setCategory(item)} className={`shrink-0 border px-3 py-2 text-xs ${category === item ? 'border-primary bg-primary text-primary-foreground' : 'border-border bg-card'}`}>{item}</button>)}</div></div></div><div className="mx-auto grid max-w-6xl gap-8 px-4 py-8 sm:px-6 lg:grid-cols-[1fr_300px]"><section><div className="mb-2 flex items-end justify-between"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-accent">Cocoa Bloom · Vadodara</p><h1 className="mt-2 font-serif text-4xl tracking-[-0.05em]">Order from the counter</h1></div><span className="font-mono text-xs text-muted-foreground">{filtered.length} items</span></div>{filtered.map((product) => <ProductRow key={product.id} product={product} liked={store.likes.includes(product.id)} onLike={() => store.toggleLike(product.id)} onAdd={() => store.addToCart(product.id)} />)}</section><OrderSummary cart={store.cart} cartCount={store.cartCount} /></div></>
}

export function OrderSummary({ cart, cartCount }: { cart: Record<string, number>; cartCount: number }) { const total = Object.entries(cart).reduce((sum, [id, count]) => sum + (getProduct(id)?.price || 0) * count, 0); return <aside className="h-fit border border-border bg-card p-5 lg:sticky lg:top-36"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-accent">Your order</p><h2 className="mt-2 font-serif text-3xl">{cartCount ? `${cartCount} treats` : 'Your bag is empty'}</h2>{cartCount ? <><div className="mt-5 flex justify-between border-t border-border pt-4 text-sm"><span>Subtotal</span><span className="font-mono">{formatPrice(total)}</span></div><div className="mt-2 flex justify-between text-sm text-muted-foreground"><span>Delivery</span><span>Free</span></div><Link href="/cart" className="mt-5 block bg-primary px-4 py-3 text-center text-xs font-semibold uppercase tracking-[0.14em] text-primary-foreground">View cart</Link></> : <Link href="/menu" className="mt-5 block border border-border px-4 py-3 text-center text-xs font-semibold uppercase tracking-[0.14em]">Browse menu</Link>}</aside> }

export function LikesView() { const store = useStore(); const likedProducts = products.filter((product) => store.likes.includes(product.id)); return <PageFrame title="Your likes" eyebrow="Saved for later">{likedProducts.length ? likedProducts.map((product) => <ProductRow key={product.id} product={product} liked onLike={() => store.toggleLike(product.id)} onAdd={() => store.addToCart(product.id)} />) : <EmptyState title="No favourites yet" text="Tap the heart on anything that makes your day a little sweeter." href="/menu" label="Browse menu" />}</PageFrame> }

export function CartView() { const store = useStore(); const items = Object.entries(store.cart).map(([id, quantity]) => ({ product: getProduct(id), quantity })).filter((item): item is { product: Product; quantity: number } => Boolean(item.product)); const total = items.reduce((sum, item) => sum + item.product.price * item.quantity, 0); return <PageFrame title="Your cart" eyebrow="Freshly packed for you">{items.length ? <div className="grid gap-8 lg:grid-cols-[1fr_320px]"><div>{items.map(({ product, quantity }) => <div key={product.id} className="flex items-center gap-3 border-b border-border py-4"><div className="relative size-20 shrink-0 overflow-hidden"><Image src={product.image} alt={product.name} fill className="object-cover" sizes="80px" /></div><div className="min-w-0 flex-1"><h3 className="font-serif text-xl">{product.name}</h3><p className="font-mono text-sm">{formatPrice(product.price)}</p></div><div className="flex items-center gap-2 border border-border px-2 py-1"><button aria-label={`Decrease ${product.name}`} onClick={() => quantity === 1 ? store.removeFromCart(product.id) : store.updateCart(product.id, quantity - 1)}><Minus size={13} /></button><span className="font-mono text-xs">{quantity}</span><button aria-label={`Increase ${product.name}`} onClick={() => store.updateCart(product.id, quantity + 1)}><Plus size={13} /></button></div><button aria-label={`Remove ${product.name}`} onClick={() => store.removeFromCart(product.id)} className="text-muted-foreground hover:text-accent"><Trash2 size={16} /></button></div>)}</div><div className="h-fit bg-primary p-5 text-primary-foreground"><p className="text-xs uppercase tracking-[0.16em] text-primary-foreground/70">Bill details</p><div className="mt-5 flex justify-between border-t border-primary-foreground/20 pt-4 text-sm"><span>Item total</span><span className="font-mono">{formatPrice(total)}</span></div><div className="mt-2 flex justify-between text-sm text-primary-foreground/70"><span>Delivery</span><span>Free</span></div><div className="mt-5 flex justify-between border-t border-primary-foreground/20 pt-4 font-serif text-2xl"><span>Total</span><span>{formatPrice(total)}</span></div><button className="mt-6 w-full bg-accent px-4 py-3 text-xs font-semibold uppercase tracking-[0.14em] text-accent-foreground">Proceed to checkout</button></div></div> : <EmptyState title="Your bag is waiting" text="Pick a box, bar, or stuffed date from the counter." href="/menu" label="Explore menu" />}</PageFrame> }

function PageFrame({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { const store = useStore(); return <main className="min-h-screen"><BrandHeader cartCount={store.cartCount} likeCount={store.likes.length} /><div className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><p className="text-xs font-semibold uppercase tracking-[0.16em] text-accent">{eyebrow}</p><h1 className="mt-2 font-serif text-5xl tracking-[-0.06em]">{title}</h1><div className="mt-8">{children}</div></div></main> }
function EmptyState({ title, text, href, label }: { title: string; text: string; href: string; label: string }) { return <div className="border border-dashed border-border bg-card px-6 py-14 text-center"><h2 className="font-serif text-3xl">{title}</h2><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-muted-foreground">{text}</p><Link href={href} className="mt-6 inline-block bg-primary px-5 py-3 text-xs font-semibold uppercase tracking-[0.14em] text-primary-foreground">{label}</Link></div> }
